/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CrossBorderAMLInterface extends Interface {
    getFunction(nameOrSignature: "bankAdmin" | "dailyVolume" | "initiateTransfer" | "isWhitelisted" | "updateComplianceStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddressFlagged" | "TransferVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'bankAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'dailyVolume', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initiateTransfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isWhitelisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateComplianceStatus', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'bankAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dailyVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateComplianceStatus', data: BytesLike): Result;
  }

  
    export namespace AddressFlaggedEvent {
      export type InputTuple = [suspiciousAddress: AddressLike];
      export type OutputTuple = [suspiciousAddress: string];
      export interface OutputObject {suspiciousAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferVerifiedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CrossBorderAML extends BaseContract {
    
    connect(runner?: ContractRunner | null): CrossBorderAML;
    waitForDeployment(): Promise<this>;

    interface: CrossBorderAMLInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bankAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    dailyVolume: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    initiateTransfer: TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isWhitelisted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    updateComplianceStatus: TypedContractMethod<
      [_user: AddressLike, _status: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bankAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'dailyVolume'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initiateTransfer'): TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isWhitelisted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateComplianceStatus'): TypedContractMethod<
      [_user: AddressLike, _status: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddressFlagged'): TypedContractEvent<AddressFlaggedEvent.InputTuple, AddressFlaggedEvent.OutputTuple, AddressFlaggedEvent.OutputObject>;
getEvent(key: 'TransferVerified'): TypedContractEvent<TransferVerifiedEvent.InputTuple, TransferVerifiedEvent.OutputTuple, TransferVerifiedEvent.OutputObject>;

    filters: {
      
      'AddressFlagged(address)': TypedContractEvent<AddressFlaggedEvent.InputTuple, AddressFlaggedEvent.OutputTuple, AddressFlaggedEvent.OutputObject>;
      AddressFlagged: TypedContractEvent<AddressFlaggedEvent.InputTuple, AddressFlaggedEvent.OutputTuple, AddressFlaggedEvent.OutputObject>;
    

      'TransferVerified(address,address,uint256)': TypedContractEvent<TransferVerifiedEvent.InputTuple, TransferVerifiedEvent.OutputTuple, TransferVerifiedEvent.OutputObject>;
      TransferVerified: TypedContractEvent<TransferVerifiedEvent.InputTuple, TransferVerifiedEvent.OutputTuple, TransferVerifiedEvent.OutputObject>;
    
    };
  }